//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PEStudio.rc
//
#define IDD_ABOUTBOX                    100
#define IDI_TABCTRLBAR					101
#define IDW_PROP_BAR                    102
#define IDD_TRACECONSOLE                103
#define IDD_CONSOLE                     103
#define IDR_MAINFRAME                   128
#define IDR_PHPDOCUMENT                 129
#define IDR_RESULTSDOCUMENT             130
#define IDR_SNIFFTOOL                   132
#define IDR_SNIFFERBAR                  133
#define IDR_ACTIONBAR                   134
#define IDB_BITMAP2                     135
#define IDR_MAINFRAME24                 136
#define IDR_SNIFFTOOL24                 137
#define IDD_SELECTPROCESS               138
#define IDR_NOTFOUNDICO                 139
#define IDD_METERBOX                    139
#define IDR_SNIFFERBAR24                140
#define IDC_SNIFFERTAB                  141
#define IDD_OPTIONS                     142
#define IDI_ICON1                       143
#define IDD_SNIFFINGOPS                 144
#define IDD_SNIFFDETAILS                145
#define IDB_ACTIONBAR24                 148
#define IDB_BITMAP1                     150
#define IDB_TABIMAGES                   150
#define IDC_PROCESSLIST                 1000
#define IDC_PS_WINDOWS                  1001
#define IDC_PROCESS_NAME                1002
#define IDC_PID                         1003
#define IDC_EXE_SZ                      1004
#define IDD_CALCULATOR                  1004
#define IDC_USER                        1005
#define IDD_SNIFFSTATS                  1005
#define IDC_EXE_SZ2                     1006
#define IDC_OPENPROCESS_STATE           1006
#define IDC_TAB1                        1006
#define IDC_OPTIONS_TAB                 1006
#define IDD_SNIFFACTIVITY               1006
#define IDD_SNIFFLOG                    1007
#define IDC_BUFFERMETER                 1008
#define IDD_SCRIPTSDLG                  1008
#define IDC_PACKETMETER                 1009
#define IDD_PHPOPS                      1009
#define IDC_GROUPBOX1                   1010
#define IDC_RICHEDIT23                  1014
#define IDC_LOGWINDOW                   1014
#define IDC_OPTIONS_OK                  1015
#define IDC_OPTIONS_OK2                 1016
#define IDC_OPTIONS_CANCEL              1016
#define IDC_CALC_MODIFBOX               1016
#define IDC_CALC_SIZEBOX                1017
#define IDC_CALC_D                      1018
#define IDC_CALC_E                      1019
#define IDC_CALC_F                      1020
#define IDC_CALC_A                      1021
#define IDC_CALC_B                      1022
#define IDC_CALC_C                      1023
#define IDC_CALC_7                      1024
#define IDC_CALC_8                      1025
#define IDC_CALC_9                      1026
#define IDC_CALC_4                      1027
#define IDC_CALC_5                      1028
#define IDC_CALC_6                      1029
#define IDC_CALC_1                      1030
#define IDC_CALC_2                      1031
#define IDC_CALC_3                      1032
#define IDC_CALC_BACKSPACE              1033
#define IDC_CALC_0                      1034
#define IDC_CALC_HEX                    1035
#define IDC_CALC_CLEAR                  1036
#define IDC_CALC_PLUS                   1037
#define IDC_CALC_MINUS                  1038
#define IDC_CALC_TIMES                  1039
#define IDC_CALC_DEVIDE                 1040
#define IDC_CALC_EQUALS                 1041
#define IDC_CALC_TOPLIST                1042
#define IDC_CALC_BOTTOMLIST             1043
#define IDC_CALC_BIN                    1044
#define IDC_CALC_OCT                    1045
#define IDC_CALC_THIRTYTWOBIT           1046
#define IDC_CALC_EIGHTBIT               1047
#define IDC_CALC_SIXTEENBIT             1048
#define IDC_CALC_SIXTYFOUR              1049
#define IDC_CALC_DEC                    1050
#define IDC_CALC_SIGNED                 1051
#define IDC_CALC_UNSIGNED               1052
#define IDC_CALC_LONG                   1053
#define IDC_CALC_SHORT                  1054
#define IDC_CALC_REAL                   1055
#define IDC_CALC_FLOATING               1056
#define IDC_CALC_VIEWBOX                1057
#define IDC_DLLNAMEEDIT                 1058
#define IDC_SNIFFMETHODBOX              1059
#define IDC_BUFFERSIZESLIDE             1060
#define IDC_BIFFERSIZELOW               1061
#define IDC_BIFFERSIZELOW2              1062
#define IDC_CALC_SIXTYFOURBIT           1062
#define IDC_BUFFERSIZETXT               1063
#define IDC_PACKETSIZESLIDER            1064
#define IDC_SENDCALLS                   1065
#define IDC_PACKETSIZETEXT              1065
#define IDC_RECVCALLS                   1066
#define IDC_BIFFERSIZELOW3              1066
#define IDC_WSASENDCALLS                1067
#define IDC_WSARECVCALLS                1068
#define IDC_SENDTOCALLS                 1069
#define IDC_AVGSIZE                     1069
#define IDC_RECVFROMCALLS               1070
#define IDC_TOTALRECVED                 1070
#define IDC_WSASENDTOCALLS              1071
#define IDC_TOTALSENT                   1071
#define IDC_WSARECVFROMCALLS            1072
#define IDC_TOTALBYTES                  1072
#define IDC_ACTIVITYGRAPH               1073
#define IDC_LIST1                       1074
#define IDC_LOGLISTBOX                  1074
#define IDC_SCRIPTLISTBOX               1080
#define IDC_PHPSAVEOUTPUT               1082
#define IDC_PHPSAVECHECK                1082
#define IDC_PHPVERSIONBOX               1083
#define ID_NEW_DATAMETHOD               32771
#define ID_NEW_DATAFORMAT               32772
#define ID_NEW_DATASCRIPT               32773
#define ID_TOOLS_OPTIONS                32774
#define ID_TOOLS_CALCULATOR             32775
#define ID_TOOLS_APPLYDATAMETHOD        32776
#define ID_TOOLS_APPLYDATAFORMAT        32777
#define ID_TOOLS_APPLYDATASCRIPT        32778
#define ID_NEW_PACKETLIST               32779
#define ID_TOOLS_FILTER                 32780
#define ID_TOOLS_FINDSTATICBUFFER       32781
#define ID_FILE_NEW32782                32782
#define ID_OPEN_PROCESS                 32783
#define ID_TRACE_CONSOLE                32784
#define ID_ACTIONS_CONSOLE              32785
#define ID_EXIT_APP                     32786
#define ID_VIEW_RESULTS_WINDOW          32787
#define ID_OPTIONS                      32788
#define ID_DATAMETHODS                  32788
#define ID_APPLY_SCRIPT                 32789
#define ID_APPLY_FORMAT                 32790
#define ID_APPLY_METHOD                 32791
#define ID_BUTTON32792                  32792
#define ID_BUTTON32793                  32793
#define ID_DATASCRIPTS                  32794
#define ID_FINDDATABUFFER               32795
#define ID_CALCULATOR                   32796
#define ID_TOOLS_EXAMPLE                32797
#define ID_BUTTON32799                  32799
#define ID_SNIFFER_START                32800
#define ID_SNIFFER_PAUSE                32801
#define ID_SNIFFER_STOP                 32802
#define ID_VIEW_MAINTOOLBAR             32803
#define ID_VIEW_TRACECONSOLE            32804
#define ID_VIEW_ACTIONSCONSOLE          32806
#define ID_VIEW_CALCULATOR              32807
#define ID_SCRIPTS                      32808
#define ID_BUTTON32812                  32812
#define ID_SCRIPTS_START                32813
#define ID_SCRIPTS_STOP                 32814
#define ID_SCRIPTS_ADD                  32815
#define ID_SCRIPTS_DELETE               32816
#define IDC_CALC_BOX                    65535
#define IDP_OLE_INIT_FAILED             32817
#define IDP_SCINTILLA_INIT_FAILED		32818
#define IDP_CONTROLS_INIT_FAILED		32819
#define IDP_RICHEDIT_INIT_FAILED		32820
#define IDP_PHPDOC_INIT_FAILED			32821
#define IDP_RESULTSDOC_INIT_FAILED		32822
#define IDP_MAIN_INIT_FAILED			32823
#define IDP_ARGS_INIT_FAILED			32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
